version: '3'

services:
  app:
    build: .
    ports:
      - "4000:4000" 
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/medbuddy
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: